export * from './components/card/MovieCard';
export * from './components/Navbar';
export * from './components/slider/Slider';
export * from './components/slider/SilderItem';
export * from './components/Loader';
export * from './components/modal/ModalPage';
export * from './components/modal/ModalSearch';
export * from './components/navbar/Search';
export * from './components/PageNotFound';
